[train]
[train.trainer]
max_epochs = 300

[train.early_stopping]
monitor = "val_loss"
mode = "min"
patience = 50

[data]
data_dir = "../data"
subtype = "HR+HER2-"
n_lines = 4
horizon = 100 # in months
batch_size = 128

[eval]
horizon_times = [100, 75, 50, 30] # in months
integration_step = 6 # the dx in the trapezoidal rule for integrating Brier score over time
