[LSTM_cell]
[LSTM_cell.MLPx]
n_layers = 14
n_units = [8, 16, 32, 32, 32, 64, 64, 64, 128, 128, 128, 256, 256, 256]
output_dim = 16

[LSTM_cell.MLPp]
n_layers = 5
n_units = [32, 32, 32, 32, 32]
output_dim = 3

[LSTM_cell.MLPsa]
input_dim = 32 # Hidden state dimension of LSTM
n_layers = 14
n_units = [32, 32, 32, 32, 32, 64, 64, 64, 128, 128, 128, 256, 256, 256]

[Optimizer]
name = "adamw"
lr = 1e-3
weight_decay = 1e-4
