[LSTM_cell]
[LSTM_cell.MLPx]
n_layers = 1
n_units = [16]
output_dim = 16

[LSTM_cell.MLPp]
n_layers = 1
n_units = [16]
output_dim = 3

[LSTM_cell.MLPsa]
input_dim = 8  
n_layers = 1
n_units = [16]

[Optimizer]
name = "adamw"
lr = 1e-2
weight_decay = 1e-4
