[MLPx]
n_layers = 2
n_units = [5, 4]
output_dim = 4

[MLPp]
n_layers = 4
n_units = [4, 3, 8, 6]
output_dim = 3

[MLPsa]
input_dim = 6 # Hiddend state dimension of LSTM
n_layers = 6
n_units = [7, 6, 5, 4, 8, 9]