lstm_hidden_length = 256
lstm_num_layers = 2
n_intervals = 100
x_embed_dim = 64
p_embed_dim = 8
init_h_hidden = [64, 64]
init_p_hidden = [128, 128]
mlpx_hidden_units = [256]
mlpp_hidden_units = [8]
mlpsa_hidden_units = [64, 64]
mlpprop_hidden_units = [64]
lr = 4.39e-04
lr_scheduler_stepsize = 17
lr_scheduler_gamma = 0.5785
weight_decay = 1.28e-04
attention = true
init_h_dropout = 0
init_p_dropout = 0
mlpx_dropout = 0.1014
mlpp_dropout = 0
mlpsa_dropout = 0.0494
mlpprop_dropout = 0
lambda_prop_loss = 0
lambda_ipm_mmd = 0
lambda_ipm_emd2 = 0
evaluation_horizon_times = [100, 75, 50, 30]
brier_integration_step = 6
